### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by BenSampo**
Laravel 7 depends on symfony/finder 5 so I've bumped the symfony/finder version

### CODE REVIEW

**Comment by romanzipp** [comment]
Again blocked by [hanneskod/readme-tester](https://github.com/hanneskod/readme-tester). Is this package really necessary?

**Comment by aat2703** [comment]
What the status on Laravel 7 support?

**Comment by joelpiccoli** [comment]
Just waiting for the 7 support to upgrade my projects! o/

**Comment by atymic** [comment]
> Again blocked by [hanneskod/readme-tester](https://github.com/hanneskod/readme-tester). Is this package really necessary?

Think PHP 7.1 support could be dropped right, as it's out of support?

**Comment by hanneskod** [comment]
Hi everyone! A lot of activity here, sorry for the late reply. I completely agree that code testing tools should not interfere with actual dependencies. Will fix later today!

**Comment by NickJorens** [comment]
Hi,

I don't mean to be rude or impatient, but this is the only dependency blocking my upgrade to Laravel 7.
Do you happen to have an ETA?

**Comment by NickJorens** [comment]
Hi, 
I don't mean to push you but this is the only package holding me back from upgrading my application to Laravel 7.x

Do you happen to know when you can approve the request?

**Comment by hanneskod** [comment]
Fixed on branch `1.0`. See #19. Released as ver `1.2.1`. Let me know if you need anything else =)

**Comment by BenSampo** [comment]
Nice one, thanks @hanneskod

**Pull request closed without merging**
